#! /bin/bash

target_file="strings.xml"

while read -r line
do
	if [[ $line =~ \<string(.+)name=\"(.+)\"\> ]];
	then
		echo "${BASH_REMATCH[0]}"
		find ./* -iname $target_file|xargs  sed -i '' "/${BASH_REMATCH[0]}/d"
	else
		echo "$line is not a string resource."
	fi
done
